# Generated by Django 4.2.3 on 2023-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/picture/'),
        ),
    ]
